return {}
-- return {
-- 	{
-- 		"akinsho/bufferline.nvim",
-- 		version = "*",
-- 		dependencies = "nvim-tree/nvim-web-devicons",
-- 		config = function()
-- 			local bufferline = require("bufferline")
-- 			bufferline.setup({
-- 				options = {
-- 					offsets = {
-- 						{
-- 							filetype = "NvimTree",
-- 							text = "File Explorer",
-- 							text_align = "center",
-- 						},
-- 					},
-- 					style_preset = bufferline.style_preset.no_italic,
-- 				},
-- 			})
-- 		end,
-- 	},
-- }
